#!/usr/bin/env bash
# Usage: nimble stop ( <alias> | <service> )
# Summary: Stop a service
# Help: Stop launchctl service.
set -e

source "${_NIMBLE_ROOT}/lib/common.sh"

# Provide nimble completions
if [ "$1" = "--complete" ]; then
    if ! [ "$2" = "--all" ]; then
        echo "--all"
    fi
    get_aliases
    if [ "$2" = "--all" ]; then
        get_services_labels
    fi
    exit
fi

if [ $# -ne 1 ]; then
    [ $# -gt 1 ] && echo "Error: Too many arguments." || \
        echo "Error: Too few arguments."
    echo "See the nimble help with the command:"
    echo "  nimble help stop"
    exit 1
fi

if is_alias $1; then
    service=$(get_alias_service $1)
    launchctl stop $service
    echo "Stopped \"$1\" service."
elif is_service $1; then
    launchctl stop $1
    echo "Stopped \"$1\" service."
else
    echo "Error: Couldn't find the service \"$1\"."
    exit 1
fi
