#!/usr/bin/env bash
set -e

print=""
if [ "$1" = "-" ]; then
  print=1
  shift
fi

shell="$1"
if [ -z "$shell" ]; then
  shell="$(basename "$SHELL")"
fi

# Create only the first time
if ! [ -f '~/.nimble.map' ]; then
    touch ~/.nimble.map
    created=1
fi

resolve_link() {
  $(type -p greadlink readlink | head -1) $1
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

root="$(abs_dirname "$0")/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    profile='~/.bash_profile'
    ;;
  zsh )
    profile='~/.zshenv'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  {
    if [ -z "$created" ]; then
        echo "Nimble service-mapping file created at ~/.nimble.map"
    fi
    echo "# Load nimble automatically by adding"
    echo "# the following to ${profile}:"
    echo
    echo "eval \"\$(${_NIMBLE_ROOT}/bin/nimble init -)\""
    echo
  } >&2

  exit 1
fi

echo "export PATH=\"\${PATH}:${_NIMBLE_ROOT}/bin\""

case "$shell" in
bash | zsh )
  echo "source \"$root/completions/nimble.${shell}\""
  ;;
esac

commands=(`nimble commands --sh`)
IFS="|"
cat <<EOS
_nimble_wrapper() {
  local command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval \`nimble "sh-\$command" "\$@"\`;;
  *)
    command nimble "\$command" "\$@";;
  esac
}
EOS

# zsh can't pass argument with aliases, but bash can.
# zsh can have functions with the name being only numbers, but bash can't.
# fix both cases here by letting zsh have a function, and bash have its alias.
case "$shell" in
bash )
  echo "alias nimble=_nimble_wrapper"
  ;;
zsh )
  echo "nimble=_nimble_wrapper"
  ;;
esac
